### ISSUE TITLE
stream from Reolink PT cannot be consumed with ffmpeg

### ISSUE THREAD

**Issue by rpnoll1977** [jdillenkofer/camera_proxy#5] opened 2020-11-08 14:43 UTC
Using a Reolink PT camera and ffmpeg on the command line as the client, i got an error message about missing boundary 

     Expected boundary '--' not found, instead found a line of n bytes

I wasnt's able to cure this using command line switches, so I changed this part to deliver content-length information to make it work.

 def frame_generator():
        while True:
            camera_stream_manager.update_last_accessed_timestamp(name)
            frame = queue.get()
            output = io.BytesIO()
            frame.save(output, 'JPEG')
            len = output.tell()
            output.seek(0)
            yield (b'--frame\r\n'
                b'Content-Type: image/jpeg\r\nContent-Length: ' + str(len).encode() + b'\r\n\r$
    return Response(frame_generator(), mimetype='multipart/x-mixed-replace; boundary=frame')

**Comment by jdillenkofer** [comment] 2020-11-08 15:33
Hi,
i added the Content-Length header to the stream response.
Can you tell me if the problem is fixed on the current develop branch?

**Comment by rpnoll1977** [comment] 2020-11-08 18:52
problem fixed, thank you

**Comment by jdillenkofer** [comment] 2020-11-08 19:33
Thanks for the help.

**Closed by jdillenkofer** 2020-11-08 19:33 UTC
